import type { getAdminReport, reportPeriod } from "@/lib/admin/reporting";
import { BarChart3, CalendarDays, CreditCard, RotateCcw, Users, Wallet, Crown, ShieldCheck, FlaskConical, Info, AlertTriangle, Layers, type LucideIcon } from "lucide-react";
const money = (value: number) => Math.round(value).toLocaleString("vi-VN") + " đ";
const number = (value: number) => value.toLocaleString("vi-VN");
const card = "rounded-2xl border border-slate-200 bg-white shadow-xs overflow-hidden min-w-0";
const cell = "px-4 sm:px-5 py-3 text-right tabular-nums whitespace-nowrap";
const firstCell = cell.replace("text-right", "text-left");
const statuses: Record<string, {
    label: string;
    color: string;
}> = {
    SUCCESS: { label: "Thành công", color: "bg-emerald-50 text-emerald-700 border-emerald-200" },
    PENDING: { label: "Chờ thanh toán", color: "bg-blue-50 text-blue-700 border-blue-200" },
    REVIEW: { label: "Cần đối soát", color: "bg-amber-50 text-amber-700 border-amber-200" },
    REFUNDED: { label: "Đã hoàn tiền", color: "bg-purple-50 text-purple-700 border-purple-200" },
    FAILED: { label: "Thất bại", color: "bg-rose-50 text-rose-700 border-rose-200" },
    EXPIRED: { label: "Hết hạn", color: "bg-slate-100 text-slate-600 border-slate-200" },
    CANCELLED: { label: "Đã hủy", color: "bg-slate-100 text-slate-600 border-slate-200" },
};
function SectionHeader({ title, subtitle, icon: Icon, tone = "blue", badge }: {
    title: string;
    subtitle: string;
    icon: LucideIcon;
    tone?: "blue" | "amber" | "purple" | "emerald";
    badge?: string;
}) {
    const colors = { blue: "bg-blue-50 border-blue-100 text-blue-600", amber: "bg-amber-50 border-amber-100 text-amber-600", purple: "bg-purple-50 border-purple-100 text-purple-600", emerald: "bg-emerald-50 border-emerald-100 text-emerald-600" };
    return <div className="px-4 sm:px-5 py-3.5 border-b border-slate-100 bg-slate-50/40 flex flex-wrap items-center justify-between gap-3">
    <div className="flex items-center gap-3 min-w-0"><div className={`w-9 h-9 rounded-xl border flex items-center justify-center shrink-0 shadow-2xs ${colors[tone]}`}><Icon size={17}/></div><div><h3 className="text-sm sm:text-base font-black text-slate-900">{title}</h3><p className="text-[11px] text-slate-500 mt-0.5 leading-relaxed">{subtitle}</p></div></div>
    {badge && <span className="rounded-full border border-slate-200 bg-white px-2.5 py-1 text-[10px] font-bold text-slate-500">{badge}</span>}
  </div>;
}
export function AdminReportDetails({ report, period }: {
    report: Awaited<ReturnType<typeof getAdminReport>>;
    period: ReturnType<typeof reportPeriod>;
}) {
    const metrics = [
        { title: "Doanh thu trước hoàn tiền", value: money(report.grossRevenue), hint: "Thanh toán VIP thật trong kỳ", icon: Wallet, color: "bg-emerald-50 text-emerald-600 border-emerald-100" },
        { title: "Hoàn tiền trong kỳ", value: money(report.refundAmount), hint: "Ghi nhận theo ngày hoàn trả", icon: RotateCcw, color: "bg-rose-50 text-rose-600 border-rose-100" },
        { title: "Lượt thanh toán trong kỳ", value: number(report.paidCount), hint: "Không gồm giao dịch thử / chờ", icon: CreditCard, color: "bg-blue-50 text-blue-600 border-blue-100" },
        { title: "ARPU trong kỳ", value: money(report.arpu), hint: `${number(report.usersAtEnd)} tài khoản trong mẫu số`, icon: Users, color: "bg-purple-50 text-purple-600 border-purple-100" },
    ];
    return <section aria-labelledby="admin-report-details" className="space-y-4 sm:space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3 pt-2">
      <div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-gradient-to-br from-indigo-600 to-purple-600 text-white flex items-center justify-center shadow-md shadow-indigo-500/15"><BarChart3 size={20}/></div><div><h2 id="admin-report-details" className="text-lg font-black text-slate-900">Báo Cáo Chi Tiết</h2><p className="text-xs text-slate-500 mt-0.5">Đối soát thanh toán, quyền VIP và nhóm tài khoản</p></div></div>
      <span className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs text-slate-600 shadow-xs"><CalendarDays size={14} className="text-indigo-500"/><span className="tabular-nums">{period.from} → {period.to}</span><span className="text-slate-400">UTC+7</span></span>
    </div>
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3.5 sm:gap-4">{metrics.map(({ icon: Icon, ...metric }) => <div key={metric.title} className={`${card} p-4 sm:p-5`}><div className={`w-10 h-10 rounded-xl border flex items-center justify-center mb-3 ${metric.color}`}><Icon size={20}/></div><p className="text-[10px] sm:text-[11px] font-bold text-slate-400 uppercase tracking-wider">{metric.title}</p><p className="mt-1 text-xl sm:text-2xl font-black font-mono tracking-tight text-slate-900 break-words">{metric.value}</p><p className="mt-1 text-[11px] text-slate-500">{metric.hint}</p></div>)}</div>
    {(report.unknownPaid > 0 || report.unknownRefund > 0) && <div role="status" className="flex items-start gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4"><AlertTriangle size={18} className="text-amber-600 shrink-0 mt-0.5"/><div><p className="text-sm font-bold text-amber-800">Dữ liệu cần đối soát</p><p className="mt-1 text-xs leading-relaxed text-amber-700">{number(report.unknownPaid)} giao dịch thiếu ngày thanh toán; {number(report.unknownRefund)} hoàn tiền thiếu ngày hoàn trả. Những bản ghi này không được cộng vào tổng theo ngày tương ứng.</p></div></div>}

    <div className="grid grid-cols-1 xl:grid-cols-2 gap-4 lg:gap-5 items-stretch">
      <section className={card}><SectionHeader title="Trạng thái yêu cầu tạo trong kỳ" subtitle="Phân loại yêu cầu thật theo ngày tạo, độc lập với ngày thanh toán" icon={ShieldCheck} badge={`${number(report.statuses.reduce((sum, row) => sum + row._count.id, 0))} yêu cầu thật`}/><div className="p-4 sm:p-5"><div className="grid grid-cols-2 sm:grid-cols-3 gap-2.5">{report.statuses.length ? report.statuses.map(row => { const status = statuses[row.status] ?? { label: row.status, color: "bg-slate-50 text-slate-600 border-slate-200" }; return <div key={row.status} className={`rounded-xl border p-3 ${status.color}`}><p className="text-[11px] font-semibold">{status.label}</p><p className="mt-1 text-2xl font-black tabular-nums">{number(row._count.id)}</p></div>; }) : <p className="col-span-full py-5 text-center text-xs text-slate-400">Chưa có yêu cầu thanh toán thật trong kỳ.</p>}</div><div className="mt-4 flex items-center justify-between gap-3 rounded-xl border border-dashed border-slate-200 bg-slate-50 px-3 py-2.5"><span className="flex items-center gap-2 text-xs text-slate-500"><FlaskConical size={15}/> Giao dịch thử · không tính doanh thu</span><strong className="text-sm font-mono text-slate-700">{number(report.sandbox)}</strong></div></div></section>
      <section className={card}><SectionHeader title="Sự kiện quyền VIP trong kỳ" subtitle="Ghi nhận từ khi triển khai, không suy ngược quyền quá khứ" icon={Crown} tone="amber" badge={`${number(report.grants.reduce((sum, row) => sum + row._count.id, 0))} sự kiện`}/><div className="p-4 sm:p-5 space-y-3">{([{ kind: "NEW", label: "Cấp mới", color: "bg-emerald-50 text-emerald-700" }, { kind: "RENEWAL", label: "Gia hạn", color: "bg-blue-50 text-blue-700" }, { kind: "REVOKED", label: "Thu hồi", color: "bg-rose-50 text-rose-700" }] as const).map(item => <div key={item.kind} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-slate-100 p-3"><span className={`rounded-lg px-2.5 py-1 text-xs font-bold ${item.color}`}>{item.label}</span><div className="flex flex-wrap gap-3 text-[11px] text-slate-500"><span>Thanh toán <strong className="ml-1 text-slate-900 tabular-nums">{number(report.grants.find(row => row.kind === item.kind && row.source === "PAYMENT")?._count.id ?? 0)}</strong></span><span>Quản trị <strong className="ml-1 text-slate-900 tabular-nums">{number(report.grants.find(row => row.kind === item.kind && row.source === "MANUAL")?._count.id ?? 0)}</strong></span></div></div>)}{!report.grants.length && <p className="text-center text-[11px] text-slate-400">Chưa có sự kiện trong kỳ.</p>}</div></section>
    </div>

    <section className={card}><SectionHeader title="Doanh thu theo ngày" subtitle="Thanh toán theo paidAt · hoàn tiền theo refundedAt · chỉ VIP thật bằng VND" icon={CalendarDays} tone="purple" badge={`${number(report.daily.length)} ngày trong kỳ`}/><div className="max-h-[400px] overflow-auto custom-scrollbar"><table className="w-full text-left text-xs min-w-[680px]"><caption className="sr-only">Doanh thu theo ngày Việt Nam trong kỳ báo cáo</caption><thead className="sticky top-0 z-10 bg-slate-50 border-b border-slate-200 text-[10px] uppercase tracking-wider text-slate-500"><tr>{["Ngày (VN)", "Trước hoàn tiền", "Hoàn tiền", "Sau hoàn tiền", "Lượt thanh toán"].map((title, i) => <th scope="col" key={title} className={`${i === 0 ? firstCell : cell} font-bold`}>{title}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{report.daily.length ? report.daily.map(row => <tr key={row.day} className="hover:bg-slate-50/70 transition-colors"><th scope="row" className={`${firstCell} font-semibold text-slate-600`}>{row.day.split("-").reverse().join("/")}</th><td className={`${cell} text-slate-700 font-mono`}>{money(row.gross)}</td><td className={`${cell} font-mono ${row.refunds ? "text-rose-600" : "text-slate-400"}`}>{money(row.refunds)}</td><td className={`${cell} font-bold font-mono ${row.gross - row.refunds < 0 ? "text-rose-600" : "text-emerald-600"}`}>{money(row.gross - row.refunds)}</td><td className={cell}><span className="inline-block min-w-7 rounded-lg bg-slate-100 px-2 py-1 text-slate-600 font-semibold">{number(row.count)}</span></td></tr>) : <tr><td colSpan={5} className="p-8 text-center text-slate-400">Chưa có dữ liệu theo ngày.</td></tr>}</tbody><tfoot className="bg-indigo-50/60 border-t border-indigo-100 font-bold"><tr><th scope="row" className={`${firstCell} text-indigo-900`}>Tổng trong kỳ</th><td className={`${cell} font-mono text-indigo-900`}>{money(report.grossRevenue)}</td><td className={`${cell} font-mono text-rose-600`}>{money(report.refundAmount)}</td><td className={`${cell} font-mono ${report.netRevenue < 0 ? "text-rose-600" : "text-emerald-700"}`}>{money(report.netRevenue)}</td><td className={`${cell} text-indigo-900`}>{number(report.paidCount)}</td></tr></tfoot></table></div></section>

    <section className={card}><SectionHeader title="Nhóm tài khoản theo tháng đăng ký" subtitle="12 tháng có tài khoản gần nhất còn lưu · thanh toán và doanh thu trong kỳ đang chọn" icon={Layers} tone="emerald" badge={`${number(report.cohorts.length)} nhóm`}/><div className="overflow-auto custom-scrollbar"><table className="w-full text-left text-xs min-w-[600px]"><caption className="sr-only">Tài khoản và thanh toán theo tháng đăng ký</caption><thead className="bg-slate-50 border-b border-slate-200 text-[10px] uppercase tracking-wider text-slate-500"><tr>{["Tháng đăng ký", "Tài khoản", "Người trả tiền trong kỳ", "Doanh thu trước hoàn tiền"].map((title, i) => <th scope="col" key={title} className={`${i === 0 ? firstCell : cell} font-bold`}>{title}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{report.cohorts.length ? report.cohorts.map(row => <tr key={row.month} className="hover:bg-slate-50/70 transition-colors"><th scope="row" className={`${firstCell} font-semibold text-slate-700`}><span className="inline-flex items-center gap-2"><Users size={14} className="text-emerald-500"/>{row.month.split("-").reverse().join("/")}</span></th><td className={`${cell} text-slate-600`}>{number(row.accounts)}</td><td className={`${cell} text-blue-600 font-semibold`}>{number(row.payers)}</td><td className={`${cell} font-mono font-bold text-emerald-600`}>{money(row.gross)}</td></tr>) : <tr><td colSpan={4} className="p-8 text-center text-slate-400">Chưa có nhóm tài khoản phù hợp.</td></tr>}</tbody></table></div><p className="px-4 sm:px-5 py-3 bg-slate-50/70 border-t border-slate-100 text-[11px] text-slate-500">Đây là nhóm theo tháng đăng ký, không phải tỷ lệ giữ chân. Doanh thu ở bảng này chưa trừ hoàn tiền.</p></section>

    <details className={`${card} group`}><summary className="flex items-center gap-2.5 px-4 sm:px-5 py-3.5 cursor-pointer text-xs font-bold text-slate-600 hover:bg-slate-50"><Info size={16} className="text-indigo-500"/> Cách tính và phạm vi báo cáo <span className="ml-auto text-slate-400 group-open:rotate-180 transition-transform" aria-hidden="true">⌄</span></summary><div className="px-4 sm:px-5 pb-4 text-xs text-slate-500 leading-relaxed space-y-2 border-t border-slate-100 pt-3"><p>Doanh thu chỉ tính thanh toán VIP thật bằng VND. Thanh toán theo ngày nhận tiền; hoàn tiền toàn phần theo ngày hoàn trả. Doanh thu sau hoàn tiền có thể âm nếu hoàn giao dịch của kỳ trước.</p><p>ARPU = doanh thu sau hoàn tiền trong kỳ / {number(report.usersAtEnd)} tài khoản còn trong database, đăng ký trước khi kết thúc kỳ, bao gồm admin. Không phải doanh thu trên người trả tiền.</p><p>Không tự gán ngày tạo thay ngày thanh toán/hoàn tiền. Sự kiện VIP chỉ ghi từ khi triển khai phiên bản mới; giao dịch thử không được cộng vào báo cáo cấp quyền.</p></div></details>
  </section>;
}
