import type { ShopType } from "../pricing/types";

export type KocPlanInput = {
  campaignName: string;
  shopType: ShopType;
  categoryId: string;
  totalBudget: number;
  sampleCost: number;
  sampleShippingCost: number;
  castFee: number;
  effectiveKocRate: number;
  videosPerKoc: number;
  organicOrdersPerEffectiveKoc: number;
  averageSellingPrice: number;
  sellerDiscountRate: number;
  platformDiscount: number;
  buyerShippingFee: number;
  costPerSoldItem: number;
  packagingCost: number;
  handlingCost: number;
  sellerShippingCost: number;
  organicCommissionRate: number;
  useAds: boolean;
  adsBudgetRate: number;
  adsCostPerOrder: number;
  adsCommissionRate: number;
  includeTikTokFees: boolean;
  platformCommissionRate: number;
  transactionFeeRate: number;
  fixedOrderFee: number;
  enabledProgramIds: string[];
  taxRate: number;
  cancellationRate: number;
  cancellationCost: number;
  deliveryFailureRate: number;
  returnRate: number;
  returnedInventoryRecoveryRate: number;
  returnCostPerOrder: number;
  nonRefundableReturnFee: number;
  damageRate: number;
  extraKocCostRate: number;
  otherOperatingCost: number;
};

export type KocPlanResult = {
  creatorBudget: number;
  costPerInvitedKoc: number;
  invitedKocs: number;
  effectiveKocs: number;
  videos: number;
  organicOrders: number;
  adOrders: number;
  expectedOrders: number;
  returnedOrders: number;
  successfulOrders: number;
  grossRevenue: number;
  netRevenue: number;
  expectedPayoutBeforeAffiliate: number;
  expectedNetSettlement: number;
  sampleAndCastCost: number;
  adSpend: number;
  organicCommission: number;
  adsCommission: number;
  platformFees: number;
  taxes: number;
  soldGoodsCost: number;
  fulfillmentCost: number;
  returnLoss: number;
  extraKocCost: number;
  totalCost: number;
  netProfit: number;
  roi: number;
  roas: number | null;
  costPerSuccessfulOrder: number | null;
  breakEvenOrders: number | null;
  breakEvenCpa: number | null;
  netMargin: number;
  unusedBudget: number;
  warnings: string[];
};
